M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu22.04.1} date 2025-11-28T11:55:00+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-28T11:55:00+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X123.5Y-124.0
X124.0Y-31.5
X214.5Y-31.5
X214.5Y-124.0
M30
